# For puppetlabs_spec_helper documentation - see http://github.com/puppetlabs/puppetlabs_spec_helper

fixtures:
  repositories:
    sysctl: 'git@github.com:PearsonEducation-Puppet/puppet-sysctl.git'
  symlinks:
    redis/files: '../../../../files'
    redis/manifests: '../../../../manifests'
    redis/templates: '../../../../templates'
